//
//  HTTPHeaderFields.swift
//  Networking-iOS
//
//  Created by Stanislav Novacek on 01/05/2018.
//  Copyright © 2018 Stanislav Novacek. All rights reserved.
//


/**
 HTTP header fields.
 */
public enum HTTPHederFields: String {
    
    case accept = "Accept"
    case acceptCharset = "Accept-Charset"
    case acceptEncoding = "Accept-Encoding"
    case acceptLanguage = "Accept-Language"
    case acceptRanges = "Accept-Ranges"
    case accessControlAllowCredentials = "Access-Control-Allow-Credentials"
    case accessControlAllowHeaders = "Access-Control-Allow-Headers"
    case accessControlAllowMethods = "Access-Control-Allow-Methods"
    case accessControlAllowOrigin = "Access-Control-Allow-Origin"
    case accessControlExposeHeaders = "Access-Control-Expose-Headers"
    case accessControlMaxAge = "Access-Control-Max-Age"
    case accessControlRequestHeaders = "Access-Control-Request-Headers"
    case accessControlRequestMethod = "Access-Control-Request-Method"
    case age = "Age"
    case allow = "Allow"
    case authorization = "Authorization"
    case cacheControl = "Cache-Control"
    case connection = "Connection"
    case contentDisposition = "Content-Disposition"
    case contentEncoding = "Content-Encoding"
    case contentLanguage = "Content-Language"
    case contentLength = "Content-Length"
    case contentLocation = "Content-Location"
    case contentRange = "Content-Range"
    case contentSecurityPolicy = "Content-Security-Policy"
    case contentSecurityPolicyReportOnly = "Content-Security-Policy-Report-Only"
    case contentType = "Content-Type"
    case cookie = "Cookie"
    case cookie2 = "Cookie2"
    case dNT = "DNT"
    case date = "Date"
    case eTag = "ETag"
    case expect = "Expect"
    case expectCT = "Expect-CT"
    case expires = "Expires"
    case forwarded = "Forwarded"
    case from = "From"
    case host = "Host"
    case ifMatch = "If-Match"
    case ifModifiedSince = "If-Modified-Since"
    case ifNoneMatch = "If-None-Match"
    case ifRange = "If-Range"
    case ifUnmodifiedSince = "If-Unmodified-Since"
    case keepAlive = "Keep-Alive"
    case largeAllocation = "Large-Allocation"
    case lastModified = "Last-Modified"
    case location = "Location"
    case origin = "Origin"
    case pragma = "Pragma"
    case proxyAuthenticate = "Proxy-Authenticate"
    case proxyAuthorization = "Proxy-Authorization"
    case publicKeyPins = "Public-Key-Pins"
    case publicKeyPinsReportOnly = "Public-Key-Pins-Report-Only"
    case range = "Range"
    case referer = "Referer"
    case referrerPolicy = "Referrer-Policy"
    case retryAfter = "Retry-After"
    case server = "Server"
    case setCookie = "Set-Cookie"
    case setCookie2 = "Set-Cookie2"
    case sourceMap = "SourceMap"
    case strictTransportSecurity = "Strict-Transport-Security"
    case te = "TE"
    case timingAllowOrigin = "Timing-Allow-Origin"
    case tk = "Tk"
    case trailer = "Trailer"
    case transferEncoding = "Transfer-Encoding"
    case upgradeInsecureRequests = "Upgrade-Insecure-Requests"
    case userAgent = "User-Agent"
    case vary = "Vary"
    case via = "Via"
    case wwwAuthenticate = "WWW-Authenticate"
    case warning = "Warning"
    case xContentTypeOptions = "X-Content-Type-Options"
    case xDNSPrefetchControl = "X-DNS-Prefetch-Control"
    case xForwardedFor = "X-Forwarded-For"
    case xForwardedHost = "X-Forwarded-Host"
    case xForwardedProto = "X-Forwarded-Proto"
    case xFrameOptions = "X-Frame-Options"
    case xXSSProtection = "X-XSS-Protection"
    case xRateLimitLimit = "X-RateLimit-Limit"
    case xRateLimitRemaining = "X-RateLimit-Remaining"
    case xRequestedWith = "X-Requested-With"
    
}
