module: SwiftRedis
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-redis/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftRedis.xcodeproj, -target, SwiftRedis, LIBRARY_SEARCH_PATHS=.build/debug]

